---
language: node_js
node_js:
- '0.10'
script: npm test
notifications:
  irc: irc.freenode.org#fbp
env:
  global:
    secure: ! 'LQGMDNNTx9ZXAuyPFUaxZ6TLM5coOaVz0+hUZN4zKDkIdf/eDUsr/SPgDrvu

      VlTxSyisrKpcJWXXvHnDkx+tIw3c9LLcPDv0RHHHIo9eB2M1hoOVBbkvBgan

      xQcAS8xYPucEehjmRX7055QuhCxvbkIn2uD2Z5Rpm+E3by3wl7g='
